### ISSUE TITLE
Container credential provider not supported

### ISSUE THREAD

**Issue by jacobemcken** [jacobemcken/aws-simple-sign#6]
Containers like EC2 and ECS have their credentials injected using:
https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html

The library doesn't currently support this.

I might be able to find inspiration here:
https://github.com/cognitect-labs/aws-api/blob/83d2556b036d4fa5dac0943c30dca554fd0e9461/src/cognitect/aws/credentials.clj#L280-L298

**Comment by calmaty** [comment]
if you are willing to use cognitec/aws-api you could use their credential provider:

https://github.com/cognitect-labs/aws-api/blob/0f0089f42c189ddf60b6ba2e0286bb71974aed63/src/cognitect/aws/client/shared.clj#L30-L36

**Comment by jacobemcken** [comment]
I tried using the Cognitect API client directly, and I think it works, but this breaks Babashka support :sob: 

https://github.com/jacobemcken/aws-simple-sign/tree/feature/cognitect-aws-client
